fixtures:
  repositories:
    # Puppetlabs
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "6.2.1"
    stdlib: 
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "5.1.0"
  symlinks:
    "corp104_prerender": "#{source_dir}"